"""add x models

Revision ID: 20715dda9c04
Revises: 
Create Date: 2026-01-10 13:42:32.466927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20715dda9c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_domains',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_entities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_entities_name'), ['name'], unique=False)

    op.create_table('x_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('possibly_sensitive', sa.Boolean(), nullable=True),
    sa.Column('reply_settings', sa.String(length=30), nullable=True),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('repost_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('bookmark_count', sa.Integer(), nullable=True),
    sa.Column('impression_count', sa.Integer(), nullable=True),
    sa.Column('in_reply_to_post_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_post_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['x_users.id'], ),
    sa.ForeignKeyConstraint(['in_reply_to_post_id'], ['x_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_posts_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_posts_created_at'), ['created_at'], unique=False)

    op.create_table('x_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_type', sa.String(length=30), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('listed_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('pinned_post_id', sa.BigInteger(), nullable=True),
    sa.Column('most_recent_post_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_profile_data', sa.JSON(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pinned_post_id'], ['x_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_users_username'), ['username'], unique=True)

    op.create_table('post_context_annotations',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('domain_id', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['annotation_domains.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['annotation_entities.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['x_posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'domain_id', 'entity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_context_annotations')
    with op.batch_alter_table('x_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_users_username'))

    op.drop_table('x_users')
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_x_posts_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_x_posts_author_id'))

    op.drop_table('x_posts')
    with op.batch_alter_table('annotation_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_entities_name'))

    op.drop_table('annotation_entities')
    op.drop_table('annotation_domains')
    # ### end Alembic commands ###
