"""add api request log

Revision ID: 700bc722dd93
Revises: 20715dda9c04
Create Date: 2026-01-10 18:36:11.658689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700bc722dd93'
down_revision = '20715dda9c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_request_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_request_logs_user_id'))

    op.drop_table('api_request_logs')
    # ### end Alembic commands ###
