"""log headers and token scopes

Revision ID: 953560851be1
Revises: c38bdadde165
Create Date: 2026-01-11 10:43:59.269428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953560851be1'
down_revision = 'c38bdadde165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_headers', sa.JSON(), nullable=True))

    with op.batch_alter_table('user_o_auth_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_o_auth_token', schema=None) as batch_op:
        batch_op.drop_column('scope')

    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.drop_column('response_headers')

    # ### end Alembic commands ###
