"""store api response body

Revision ID: c38bdadde165
Revises: 700bc722dd93
Create Date: 2026-01-10 18:52:44.748737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38bdadde165'
down_revision = '700bc722dd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_body', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.drop_column('response_body')

    # ### end Alembic commands ###
