"""initial

Revision ID: c9c0e438a4f3
Revises: 
Create Date: 2026-01-13 22:02:50.042498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c0e438a4f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_domains',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_entities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_entities_name'), ['name'], unique=False)

    op.create_table('app_vars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=190), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('x_news_story_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_news_data', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_news_story_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_news_story_snapshots_news_id'), ['news_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_news_story_snapshots_source'), ['source'], unique=False)

    op.create_table('x_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('possibly_sensitive', sa.Boolean(), nullable=True),
    sa.Column('reply_settings', sa.String(length=30), nullable=True),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('repost_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('bookmark_count', sa.Integer(), nullable=True),
    sa.Column('impression_count', sa.Integer(), nullable=True),
    sa.Column('in_reply_to_post_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_post_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['x_users.id'], ),
    sa.ForeignKeyConstraint(['in_reply_to_post_id'], ['x_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_posts_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_posts_created_at'), ['created_at'], unique=False)

    op.create_table('x_trend_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('woeid', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('trend_name', sa.String(length=255), nullable=False),
    sa.Column('tweet_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('trending_since', sa.String(length=80), nullable=True),
    sa.Column('raw_trend_data', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_trend_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_trend_snapshots_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_trend_snapshots_trend_name'), ['trend_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_trend_snapshots_woeid'), ['woeid'], unique=False)

    op.create_table('x_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_type', sa.String(length=30), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('listed_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('pinned_post_id', sa.BigInteger(), nullable=True),
    sa.Column('most_recent_post_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_profile_data', sa.JSON(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pinned_post_id'], ['x_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_users_username'), ['username'], unique=True)

    op.create_table('api_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_request_logs_user_id'), ['user_id'], unique=False)

    op.create_table('post_context_annotations',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('domain_id', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['annotation_domains.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['annotation_entities.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['x_posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'domain_id', 'entity_id')
    )
    op.create_table('user_linked_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('x_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'x_user_id', name='uq_owner_x')
    )
    op.create_table('user_o_auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('x_user_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'x_user_id', name='uq_token_owner_x')
    )
    op.create_table('x_media_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('x_user_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('media_category', sa.String(length=40), nullable=True),
    sa.Column('media_type', sa.String(length=60), nullable=True),
    sa.Column('output_format', sa.String(length=20), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('stored_size', sa.Integer(), nullable=True),
    sa.Column('upload_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('media_id', sa.String(length=32), nullable=True),
    sa.Column('media_key', sa.String(length=64), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('file_blob', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_media_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_media_uploads_user_id'), ['user_id'], unique=False)

    op.create_table('x_spaces',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('is_ticketed', sa.Boolean(), nullable=True),
    sa.Column('raw_space_data', sa.JSON(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['x_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_spaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_spaces_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_x_spaces_state'), ['state'], unique=False)

    op.create_table('x_usage_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('cap_reset_day', sa.Integer(), nullable=True),
    sa.Column('project_cap', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('project_usage', sa.Integer(), nullable=True),
    sa.Column('daily_project_usage', sa.JSON(), nullable=True),
    sa.Column('daily_client_app_usage', sa.JSON(), nullable=True),
    sa.Column('raw_usage_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_usage_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_usage_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('x_space_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('raw_space_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['x_spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('x_space_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_x_space_snapshots_space_id'), ['space_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_space_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_space_snapshots_space_id'))

    op.drop_table('x_space_snapshots')
    with op.batch_alter_table('x_usage_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_usage_snapshots_user_id'))

    op.drop_table('x_usage_snapshots')
    with op.batch_alter_table('x_spaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_spaces_state'))
        batch_op.drop_index(batch_op.f('ix_x_spaces_creator_id'))

    op.drop_table('x_spaces')
    with op.batch_alter_table('x_media_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_media_uploads_user_id'))

    op.drop_table('x_media_uploads')
    op.drop_table('user_o_auth_token')
    op.drop_table('user_linked_account')
    op.drop_table('post_context_annotations')
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_request_logs_user_id'))

    op.drop_table('api_request_logs')
    with op.batch_alter_table('x_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_users_username'))

    op.drop_table('x_users')
    with op.batch_alter_table('x_trend_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_trend_snapshots_woeid'))
        batch_op.drop_index(batch_op.f('ix_x_trend_snapshots_trend_name'))
        batch_op.drop_index(batch_op.f('ix_x_trend_snapshots_source'))

    op.drop_table('x_trend_snapshots')
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_x_posts_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_x_posts_author_id'))

    op.drop_table('x_posts')
    with op.batch_alter_table('x_news_story_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_x_news_story_snapshots_source'))
        batch_op.drop_index(batch_op.f('ix_x_news_story_snapshots_news_id'))

    op.drop_table('x_news_story_snapshots')
    op.drop_table('user')
    op.drop_table('item')
    op.drop_table('app_vars')
    with op.batch_alter_table('annotation_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_entities_name'))

    op.drop_table('annotation_entities')
    op.drop_table('annotation_domains')
    # ### end Alembic commands ###
